### ISSUE TITLE
automatic deletion of downloaded product zip after extraction

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#144]
Provide the ability to automatically delete the downloaded zip if extraction has been activated and has succeeded.

&rarr; add a new entry in user config for managing this deletion (default = True)

**Comment by sbrunato** [comment]
proposed configuration with `delete_archive` :
```yaml 
   download:
        extract: true
        outputs_prefix: "some/path"
        delete_archive: false
```

**Comment by maximlt** [comment]
Originally from @floriandeboissieu in #252 :

> By the way, I think it would be wise to use a temporary directory (tempfile.TemporaryDirectory) while extracting to avoid partially extracted files if interrupted.

**Comment by iliion** [comment]
I have the following configuration (for Onda DIAS) but it seems that the 

> delete_archive: true

 doesnt have any effect. The zipped files are  not removed.
```
onda:
    priority:
    search:
    download:
        extract:
        outputs_prefix: workspace/products/
        delete_archive: true
```
