### ISSUE TITLE
Geodes & Geodes_s3 have the same key in pre release 3.1.0b2

### ISSUE THREAD

**Issue by andretheronsa** [CS-SI/eodag#1530]
**Describe the bug**

- The latest pre-release adds geodes_s3 for internal access the CNES data lake
- The latest provider config uses the same key
```
- geodes:
    priority: # Lower value means lower priority (Default: 0)
    search: # Search parameters configuration
    auth:
        credentials:
            apikey:
    download:
        extract:
        output_dir:
geodes:
    priority: # Lower value means lower priority (Default: 0)
    search: # Search parameters configuration
    auth:
        credentials:
            aws_access_key_id:
            aws_secret_access_key:
            aws_session_token:
    download:
        extract:
        output_dir:
```
- This breaks the public Geodes access with error: `MisconfiguredError('The following credentials are missing for provider geodes: aws_access_key_id, aws_secret_access_key, aws_session_token')`
