### ISSUE TITLE
Query fields discrepancies

### ISSUE THREAD

**Issue by remi-braun** [CS-SI/eodag#154]
Hello,

I was trying to make generic field filtering on queries when I noticed some discrepancies between these fields.

For example, I looked for polarization channels with a S1 query and I got for the following providers:

| | PEPS | SOBLOO | MUNDI | CREODIAS| ONDA |
|--- | --- | --- | --- | --- | ---|
|`polarizationMode` | "VV VH" |  |  | |
|`polarization` |  |  |  | "VV VH"|
|`polarizationChannels` |  | "VV VH" | "VV/VH" | |
|*field not available*|  |   | |  | **X** |

I know it is very very difficult to harmonize the query fields for all providers.
A workaround could be to check and list the common fields somewhere in the document and harmonize them little by little.

**The goal would be of course to have a unique keyword with a unique formatting for every provider in order to do some field query without having any input about the provider.**

Best Regards,

Rémi

PS: I know that I could alter the providers.yml file to force creodias' `polarization` to `polarizationMode`, but it will be overwritten as soon as a new version of EoDag will be published

PPS: The CSV file given in the doc is not really handy to use, and does not resolve this issue

**Comment by sbrunato** [comment]
Hello Remi,
thank you very much for pointing out at this issue. 
If you find other misconfigured parameters, thanks for telling us.

Looking at http://docs.opengeospatial.org/is/13-026r9/13-026r9.html#table_7, it seems that the parameter name should be `polarizationChannels` in your case.

We will fix this issue, but  before it is done you can manually update providers config:
- dynamically, using python API:
```py
dag = EODataAccessGateway()
dag.update_providers_config("""
creodias:
    search:
        metadata_mapping:
            polarizationChannels: '$.properties.polarisation'
""")
```
- in your user settings file `~/.config/eodag/eodag.yml`:
```yaml
creodias:
    priority: # Lower value means lower priority (Default: 0)
    search:   # Search parameters configuration
        metadata_mapping:
            polarizationChannels: '$.properties.polarisation'
    download:
        extract:
        outputs_prefix:
    auth:
        credentials:
            username:
            password:
```
