### ISSUE TITLE
Allow multiple download or auth plugins for a single provider

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#1617]
Allow multiple download or auth plugins for a single provider:

```yml
!provider
  name: foo_provider
  search: !plugin
    type: StacSearch
    [...]
  download:
    - !plugin
      type: HTTPDownload
      match: 
        href: https://[-\w]+.foo.bar
    - !plugin
      type: AwsDownload
      match: 
        href: s3://
  auth:
    - !plugin
      type: GenericAuth
      match: 
        roles:
          - archive
    - !plugin
      type: AwsAuth
      match: 
        href: s3://
```

Use `matching_url` to choose appropriate plugin when using `EOProduct.register_downloader` method. 

This feature will be useful when `Asset.register_downloader` is available.
