### ISSUE TITLE
New search config entry assets_mapping

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#1618]
Allow individual asset definition using a new search config entry `assets_mapping`:

```yml
!provider
  name: foo_provider
  search: !plugin
    type: StacSearch
    metadata_mapping:
      assets: '$.assets'
    assets_mapping:
      data:
        href: '$.path.to.downloadLink'
        roles:
          - archive
        title: Full product archive
```
