### ISSUE TITLE
Document how to search products that are not referenced in eodag's catalog

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#177]
eodag maintains a [providers configuration file](https://github.com/CS-SI/eodag/blob/develop/eodag/resources/providers.yml) that lists for each provider the products that eodag makes easily available to its users.

Each product referenced in the providers configuration file is also referenced in the [product types configuration file](https://github.com/CS-SI/eodag/blob/develop/eodag/resources/product_types.yml), which provides for each product type a set of metadata, such as :
```yaml
S3_SLSTR_L2LST:
  abstract: |
    The SLSTR Level-2 LST product provides land surface parameters generated on the wide 1 km measurement grid.
    It contains measurement file with Land Surface Temperature (LST) values with associated parameters (LST
    parameters are computed and provided for each pixel (re-gridded or orphan) included in the 1 km measurement grid)
  instrument: SLSTR
  platform: SENTINEL3
  platformSerialIdentifier: S3A,S3B
  processingLevel: L2
  sensorType: OPTICAL
  license: proprietary
  title: SENTINEL3 SLSTR Level-2 LST
  missionStartDate: "2016-02-16T00:00:00Z"
```

This metadata is added to the properties of the `EOProduct`s returned by a search. This config/catalog also allows to search for products that match one or more of these metadata (e.g. optical products with search(`sensorType="OPTICAL")`).

While eodag tries to support as many product types as possible, it happens sometimes that one would like to search for a product type not available in eodag's catalog. This use case is actually already supported!

This exemple shows how to search for Sentinel 1 GRD products, known as `S1_SAR_GRD` in eodag's catalog, with the provider `astraea_eod`:
```python
>>> from eodag import EODataAccessGateway
>>> dag = EODataAccessGateway()
#  product types supported by eodag for astraea_eod:
>>> [pt["ID"] for pt in dag.list_product_types(provider="astraea_eod")]
['GENERIC_PRODUCT_TYPE', 'L8_OLI_TIRS_C1L1', 'MODIS_MCD43A4', 'NAIP', 'S2_MSI_L1C', 'S2_MSI_L2A']
# providers supported by eodag that make S1_SAR_GRD products available
>>> dag.available_providers(product_type="S1_SAR_GRD")
['aws_eos', 'creodias', 'mundi', 'onda', 'peps', 'sobloo', 'wekeo']
```
The above snippet shows that this product isn't available with `astraea_eod`. However we can find on the [STAC Index](https://stacindex.org/catalogs/astraea-earth-ondemand#/5WpJuuvfexLDmorjkAGQ8X6oLkYte2k9UcLiQ6wm) that this product is actually available with `astraea_eod` and that its name is `sentinel1_l1c_grd`.

In that case we can use this collection name, unknown to eodag, to actually search for these products on `astraea_eod`:
```python
>>> dag.set_preferred_provider("astraea_eod")
>>> prods, _ = dag.search(productType="sentinel1_l1c_grd")
>>> prods[0]
EOProduct(id=S1A_IW_GRDH_1SDV_20190905T075654_20190905T075712_028883_034613_51EB, provider=astraea_eod)
```

* [x] This capability should be documented.
* [ ] Maybe, remove the `GENERIC_PRODUCT_TYPE` returned by `dag.list_product_types()`
* [x] Provide more details to developers/contributors of eodag about how to use/set `GENERIC_PRODUCT_TYPE`
