### ISSUE TITLE
Add eocloud for L2A products

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#23]
**[Original report](https://bitbucket.org/geostorm/eodag/issue/23) by Baptiste Meylheuc (Bitbucket: [bmeylheuc](https://bitbucket.org/bmeylheuc), ).**

----------------------------------------

**S2_MSI_L2Ap** product type is not yet searched on eocloud.

Add   something like that (works on my side) in **providers.yml** in eocloud section :

```
#!yaml


 S2_MSI_L2Ap:
      product_type: L2A
      collection: Sentinel2
```
