### ISSUE TITLE
`search_all` doesn't work with Earch Search

### ISSUE THREAD

**Issue by maximlt** [CS-SI/eodag#270]
Opening this one to track an issue with `Earth-Search`.

The `next` link returned by a search request (check [this one](https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00:00:00.000Z/2020-08-16T00:00:00.000Z&bbox=[137.772897,0.0,153.749135,60.0]&collections=[%22sentinel-s2-l1c%22]&limit=2&page=1) for instance) is wrong:
```
https://earth-search.aws.element84.com/v0/search?datetime=2020-08-08T00%3A00%3A00.000Z%2F2020-08-16T00%3A00%3A00.000Z&intersects=%5Bobject%20Object%5D&collections[]=sentinel-s2-l1c&page=2&limit=2
```
It has lost the geometry (bbox) information.

I've sent an email to Earth Search to report that.

However, it seems that the next page request (e.g. `page=2`) works properly with Earth Search. We could rely override its search config (inherited from `stac_providers.yml`) to not rely on the automatic next page URL retrieval:
```yaml
  search: !plugin
    type: StacSearch
    api_endpoint: https://earth-search.aws.element84.com/v0/search
    pagination:
      next_page_url_key_path: null  # Set to null/None to dismiss it
```
