### ISSUE TITLE
Extract the contents of zip files without redundant folder

### ISSUE THREAD

**Issue by iliion** [CS-SI/eodag#396]
I launch eodag with the following _eodag.yml_ configuration

```
.
onda:
    priority: 
    search: 
    download:
        extract:
        outputs_prefix: workspace/products/
.
```

When I use the function to download and extract the products  `dag.download_all(products_to_download)` I get the following folder structure:

>  ~/workspace/products/product_x.SAFE/product_x.SAFE/*

Is this kind of redundancy  the normal behavior?

**Instead** what I would like to do is to create a folder with the extracted files (.SAFE) that will have the following structure:

>  ~/workspace/products/product_x.SAFE/*

Is it feasible?
