### ISSUE TITLE
simplify wekeo conf using querymetadata endpoint

### ISSUE THREAD

**Issue by sbrunato** [CS-SI/eodag#847]
Remove constraints from `providers.yml` and get them from https://wekeo-broker.apps.mercator.dpi.wekeo.eu/databroker/querymetadata/{collection}.

Example:
```yaml
    ERA5_PL:
      productType: EO:ECMWF:DAT:REANALYSIS_ERA5_PRESSURE_LEVELS
      providerProductType: '$.constraints.product_type'
      variable: '$.constraints.variable'
      pressure_level: '$.constraints.pressure_level'
```
instead of
```yaml
    ERA5_PL:
      productType: EO:ECMWF:DAT:REANALYSIS_ERA5_PRESSURE_LEVELS
      providerProductType:
        - ensemble_mean
        - ensemble_members
        - reanalysis
        - ensemble_spread
      variable:
        - temperature
        - fraction_of_cloud_cover
        - geopotential
        - ozone_mass_mixing_ratio
        - potential_vorticity
        - relative_humidity
        - specific_cloud_ice_water_content
        - specific_cloud_liquid_water_content
        - specific_humidity
        - specific_rain_water_content
        - specific_snow_water_content
        - vertical_velocity
        - vorticity
      pressure_level:
        - "1"
        - "2"
        - "3"
        - "5"
        - "7"
        - "10"
        - "20"
        - "30"
        - "50"
        - "70"
        - "100"
        - "125"
        - "150"
        - "175"
        - "200"
        - "225"
        - "250"
        - "300"
        - "350"
        - "400"
        - "450"
        - "500"
        - "550"
        - "600"
        - "650"
        - "700"
        - "750"
        - "775"
        - "800"
        - "825"
        - "850"
        - "875"
        - "900"
        - "925"
        - "950"
        - "975"
        - "1000"
```
